# Generated by Django 3.2.8 on 2021-10-19 14:23

from django.db import migrations, models
import webshop_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(default='', upload_to=webshop_app.models.upload_path)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
