# Generated by Django 3.2.9 on 2021-12-11 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webshop_app', '0003_sensormodel_sensorvaluemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensorvaluemodel',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop_app.sensormodel'),
        ),
    ]
